// Command opgen reads an OpenAPI YAML spec and writes a Go source file exposing the
// default server URL and the list of declared operations (method + path). It backs the
// openapi package's `go:generate` directive.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"

	"gopkg.in/yaml.v3"
)

var httpMethods = map[string]bool{
	"get": true, "post": true, "put": true, "patch": true, "delete": true,
}

type spec struct {
	Servers []struct {
		URL string `yaml:"url"`
	} `yaml:"servers"`
	Paths map[string]map[string]any `yaml:"paths"`
}

type operation struct {
	Method string
	Path   string
}

func main() {
	in := flag.String("in", "", "path to openapi.yaml")
	out := flag.String("out", "", "path to write generated.go")
	flag.Parse()

	if *in == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "opgen: -in and -out are required")
		os.Exit(1)
	}

	if err := run(*in, *out); err != nil {
		fmt.Fprintf(os.Stderr, "opgen: %v\n", err)
		os.Exit(1)
	}
}

func run(inPath, outPath string) error {
	data, err := os.ReadFile(inPath)
	if err != nil {
		return fmt.Errorf("reading %s: %w", inPath, err)
	}

	var s spec
	if err := yaml.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("parsing %s: %w", inPath, err)
	}

	if len(s.Servers) == 0 || s.Servers[0].URL == "" {
		return fmt.Errorf("%s: no servers[0].url found", inPath)
	}
	serverURL := s.Servers[0].URL

	var ops []operation
	for path, methods := range s.Paths {
		for method := range methods {
			if !httpMethods[method] {
				continue
			}
			ops = append(ops, operation{Method: method, Path: path})
		}
	}
	sort.Slice(ops, func(i, j int) bool {
		if ops[i].Path != ops[j].Path {
			return ops[i].Path < ops[j].Path
		}
		return ops[i].Method < ops[j].Method
	})

	var buf bytes.Buffer
	buf.WriteString("// Code generated by internal/opgen from API/openapi.yaml. DO NOT EDIT.\n\n")
	buf.WriteString("package openapi\n\n")
	fmt.Fprintf(&buf, "// DefaultServerURL is the API server URL declared by API/openapi.yaml.\n")
	fmt.Fprintf(&buf, "const DefaultServerURL = %q\n\n", serverURL)
	buf.WriteString("// Operations lists every method+path pair declared in API/openapi.yaml.\n")
	buf.WriteString("var Operations = []Operation{\n")
	for _, op := range ops {
		fmt.Fprintf(&buf, "\t{Method: %q, Path: %q},\n", upperMethod(op.Method), op.Path)
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated source: %w", err)
	}

	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}
	return nil
}

func upperMethod(m string) string {
	switch m {
	case "get":
		return "GET"
	case "post":
		return "POST"
	case "put":
		return "PUT"
	case "patch":
		return "PATCH"
	case "delete":
		return "DELETE"
	default:
		return m
	}
}
