// Code generated by internal/opgen from API/openapi.yaml. DO NOT EDIT.

package openapi

// DefaultServerURL is the API server URL declared by API/openapi.yaml.
const DefaultServerURL = "https://api.drivethrurpg.com/api"

// Operations lists every method+path pair declared in API/openapi.yaml.
var Operations = []Operation{
	{Method: "POST", Path: "/{DTRPG_API_VERSION}/auth_key"},
	{Method: "GET", Path: "/{DTRPG_API_VERSION}/order_products"},
	{Method: "GET", Path: "/{DTRPG_API_VERSION}/order_products/{orderProductId}"},
	{Method: "GET", Path: "/{DTRPG_API_VERSION}/order_products/{orderProductId}/prepare"},
	{Method: "GET", Path: "/{DTRPG_API_VERSION}/product_list_items"},
	{Method: "GET", Path: "/{DTRPG_API_VERSION}/product_lists"},
}
