name: CI

on:
  push:
    branches: [develop]

permissions:
  contents: read

concurrency: ci

jobs:
  test:
    name: Validate

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Go
        id: install_go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Check formatting
        id: check_fmt
        run: |
          test -z "$(gofmt -l .)"

      - name: Vet
        id: vet
        run: |
          go vet ./...

      - name: Lint
        id: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Test
        id: test
        run: |
          go test -race ./...
